export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT_DETAILS = 'FETCH_RESTAURANT_DETAILS';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_ACTIVE_RESTAURANT_INDEX = 'SET_ACTIVE_RESTAURANT_INDEX';